# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "base camp"
description: "The base camp is an area used for staging an attempt at the summit."

email: jbreitbart@gmail.com
#blog logo
logo: "/assets/images/author.png"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Jens Breitbart'
author: 'Jens Breitbart'
author_image: "/assets/images/author.png"

paginate: 5

url: "https://blog.jensbreitbart.de" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
#  - icon:	github
#    url:	https://github.com/jbreitbart
#    desc:	Follow me on github
#    share_url:
#    share_title:
#    share_link:
#
#  - icon:	linkedin
#    url:	https://de.linkedin.com/pub/jens-breitbart/32/77a/883
#    desc:	Connect to me on linked-in
#    share_url:
#    share_title:
#    share_link:
